# Generated by Django 5.1.7 on 2025-04-02 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportauser',
            name='full_name',
            field=models.CharField(max_length=350),
        ),
    ]
